
spring:

  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order_service_clean_architecture
    # url: jdbc:postgresql://order-db:5432/order_service_clean_architecture

    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update        # create, create-drop, update, none
    show-sql: true            # log SQL ra console
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Optional: Log format dễ đọc hơn
  jpa.properties.hibernate.format_sql: true

server:
  port: 8080

restaurant-service:
  # GIẢ ĐỊNH: Dịch vụ Nhà hàng đang chạy trên localhost:8081
  url: http://localhost:8081 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    com.example.demo.adapters.out.external.api.RestaurantServiceApi: DEBUG 
    feign.Logger: DEBUG


